project_id = "bdvwfddzihsvfgstlmqc"

[functions.get-languages]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.improve-prompt]
verify_jwt = true

[functions.calculate-tokens]
verify_jwt = true

[functions.test-connection]
verify_jwt = true

[functions.mcp-server]
verify_jwt = true

[functions.mcp-configure-service]
verify_jwt = true

[functions.mcp-manage-token]
verify_jwt = true
